"use strict";(self.webpackChunksic_ui=self.webpackChunksic_ui||[]).push([[3103],{10808:function(f,m,n){n.r(m),n.d(m,{demos:function(){return v}});var c=n(15009),u=n.n(c),U=n(99289),o=n.n(U),p=n(67294),d=n(5271),v={"uploadui-demo-0":{component:p.memo(p.lazy(o()(u()().mark(function l(){var a,s,t,i;return u()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,Promise.resolve().then(n.bind(n,5271));case 2:return a=e.sent,s=a.UploadUI,t=a.TextUI,i=function(){return p.createElement(s,null,p.createElement(t,null,"\u70B9\u51FB\u4E0A\u4F20"))},e.abrupt("return",{default:i});case 7:case"end":return e.stop()}},l)})))),asset:{type:"BLOCK",id:"uploadui-demo-0",refAtomIds:["UploadUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { UploadUI, TextUI } from 'sic-ui';

const App: React.FC = () => {
  return (
    <UploadUI>
      <TextUI>\u70B9\u51FB\u4E0A\u4F20</TextUI>
    </UploadUI>
  );
};
export default App;`},"sic-ui":{type:"NPM",value:"0.7.4"}},entry:"index.tsx"},context:{"sic-ui":d},renderOpts:{compile:function(){var l=o()(u()().mark(function s(){var t,i=arguments;return u()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(7335).then(n.bind(n,37335));case 2:return e.abrupt("return",(t=e.sent).default.apply(t,i));case 3:case"end":return e.stop()}},s)}));function a(){return l.apply(this,arguments)}return a}()}},"uploadui-demo-1":{component:p.memo(p.lazy(o()(u()().mark(function l(){var a,s,t;return u()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(n.bind(n,5271));case 2:return a=r.sent,s=a.UploadUI,t=function(){return p.createElement(s,{mode:2,backgroundImage:"https://file.stlg.com.cn/web_assets/license.png"})},r.abrupt("return",{default:t});case 6:case"end":return r.stop()}},l)})))),asset:{type:"BLOCK",id:"uploadui-demo-1",refAtomIds:["UploadUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { UploadUI } from 'sic-ui';

const App: React.FC = () => {
  return <UploadUI mode={2} backgroundImage="https://file.stlg.com.cn/web_assets/license.png" />;
};
export default App;`},"sic-ui":{type:"NPM",value:"0.7.4"}},entry:"index.tsx"},context:{"sic-ui":d},renderOpts:{compile:function(){var l=o()(u()().mark(function s(){var t,i=arguments;return u()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(7335).then(n.bind(n,37335));case 2:return e.abrupt("return",(t=e.sent).default.apply(t,i));case 3:case"end":return e.stop()}},s)}));function a(){return l.apply(this,arguments)}return a}()}},"uploadui-demo-2":{component:p.memo(p.lazy(o()(u()().mark(function l(){var a,s,t;return u()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(n.bind(n,5271));case 2:return a=r.sent,s=a.UploadUI,t=function(){return p.createElement(s,{mode:3})},r.abrupt("return",{default:t});case 6:case"end":return r.stop()}},l)})))),asset:{type:"BLOCK",id:"uploadui-demo-2",refAtomIds:["UploadUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { UploadUI } from 'sic-ui';

const App: React.FC = () => {
  return <UploadUI mode={3} />;
};
export default App;`},"sic-ui":{type:"NPM",value:"0.7.4"}},entry:"index.tsx"},context:{"sic-ui":d},renderOpts:{compile:function(){var l=o()(u()().mark(function s(){var t,i=arguments;return u()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(7335).then(n.bind(n,37335));case 2:return e.abrupt("return",(t=e.sent).default.apply(t,i));case 3:case"end":return e.stop()}},s)}));function a(){return l.apply(this,arguments)}return a}()}},"uploadui-demo-3":{component:p.memo(p.lazy(o()(u()().mark(function l(){var a,s,t;return u()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(n.bind(n,5271));case 2:return a=r.sent,s=a.UploadUI,t=function(){return p.createElement(s,{mode:4})},r.abrupt("return",{default:t});case 6:case"end":return r.stop()}},l)})))),asset:{type:"BLOCK",id:"uploadui-demo-3",refAtomIds:["UploadUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { UploadUI } from 'sic-ui';

const App: React.FC = () => {
  return <UploadUI mode={4} />;
};
export default App;`},"sic-ui":{type:"NPM",value:"0.7.4"}},entry:"index.tsx"},context:{"sic-ui":d},renderOpts:{compile:function(){var l=o()(u()().mark(function s(){var t,i=arguments;return u()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(7335).then(n.bind(n,37335));case 2:return e.abrupt("return",(t=e.sent).default.apply(t,i));case 3:case"end":return e.stop()}},s)}));function a(){return l.apply(this,arguments)}return a}()}},"uploadui-demo-4":{component:p.memo(p.lazy(o()(u()().mark(function l(){var a,s,t;return u()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(n.bind(n,5271));case 2:return a=r.sent,s=a.UploadUI,t=function(){return p.createElement(s,{mode:5,title:"\u793A\u4F8B\u56FE",backgroundImage:"https://file.stlg.com.cn/web_assets/logo_black.png"})},r.abrupt("return",{default:t});case 6:case"end":return r.stop()}},l)})))),asset:{type:"BLOCK",id:"uploadui-demo-4",refAtomIds:["UploadUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { UploadUI } from 'sic-ui';

const App: React.FC = () => {
  return <UploadUI mode={5} title="\u793A\u4F8B\u56FE" backgroundImage="https://file.stlg.com.cn/web_assets/logo_black.png" />;
};
export default App;`},"sic-ui":{type:"NPM",value:"0.7.4"}},entry:"index.tsx"},context:{"sic-ui":d},renderOpts:{compile:function(){var l=o()(u()().mark(function s(){var t,i=arguments;return u()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(7335).then(n.bind(n,37335));case 2:return e.abrupt("return",(t=e.sent).default.apply(t,i));case 3:case"end":return e.stop()}},s)}));function a(){return l.apply(this,arguments)}return a}()}},"uploadui-demo-5":{component:p.memo(p.lazy(o()(u()().mark(function l(){var a,s,t;return u()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,Promise.resolve().then(n.bind(n,5271));case 2:return a=r.sent,s=a.UploadUI,t=function(){return p.createElement(s,{mode:6})},r.abrupt("return",{default:t});case 6:case"end":return r.stop()}},l)})))),asset:{type:"BLOCK",id:"uploadui-demo-5",refAtomIds:["UploadUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { UploadUI } from 'sic-ui';

const App: React.FC = () => {
  return <UploadUI mode={6} />;
};
export default App;`},"sic-ui":{type:"NPM",value:"0.7.4"}},entry:"index.tsx"},context:{"sic-ui":d},renderOpts:{compile:function(){var l=o()(u()().mark(function s(){var t,i=arguments;return u()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(7335).then(n.bind(n,37335));case 2:return e.abrupt("return",(t=e.sent).default.apply(t,i));case 3:case"end":return e.stop()}},s)}));function a(){return l.apply(this,arguments)}return a}()}}}},86074:function(f,m,n){n.r(m),n.d(m,{texts:function(){return c}});const c=[{value:"\u56FD\u4FE1\u7075\u5DE5\u540E\u53F0\u7BA1\u7406\u7CFB\u7EDF-\u4E0A\u4F20\u7EC4\u4EF6",paraId:0},{value:`\u{1F48E} \u57FA\u7840\u4F7F\u7528
\u4E0A\u4F20\u7EC4\u4EF6`,paraId:1,tocIndex:2},{value:"\u{1F48E} \u8EAB\u4EFD\u8BC1\u3001\u8425\u4E1A\u6267\u7167\u4E0A\u4F20",paraId:2},{value:"\u{1F48E} \u62D6\u62FD\u4E0A\u4F20",paraId:3},{value:"\u{1F48E} \u7167\u7247\u5899",paraId:4},{value:"\u{1F48E} \u7167\u7247\u5899 \u5E26 \u793A\u4F8B\u56FE",paraId:5},{value:"\u{1F48E} \u5217\u8868\u6309\u94AE\u4E0A\u4F20",paraId:6}]}}]);
