"use strict";(self.webpackChunksic_ui=self.webpackChunksic_ui||[]).push([[892],{82883:function(c,u,e){e.r(u),e.d(u,{demos:function(){return _}});var o=e(15009),l=e.n(o),p=e(99289),i=e.n(p),a=e(67294),I=e(17069),_={"emptyui-demo-0":{component:a.memo(a.lazy(i()(l()().mark(function m(){var t,r,s,d;return l()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,Promise.resolve().then(e.bind(e,17069));case 2:return t=n.sent,r=t.EmptyUI,s=t.ImageUI,d=t.Space,n.abrupt("return",{default:function(){return a.createElement(d,null,a.createElement(r,null),a.createElement(r,{image:a.createElement(s,{src:"https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",width:177,height:144})}),a.createElement(r,{text:"\u6682\u65E0\u6570\u636E"}))}});case 7:case"end":return n.stop()}},m)})))),asset:{type:"BLOCK",id:"emptyui-demo-0",refAtomIds:["EmptyUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { EmptyUI, ImageUI, Space } from 'sic-ui';

export default () => (
  <Space>
    <EmptyUI />
    <EmptyUI
      image={<ImageUI src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" width={177} height={144} />}
    />
    <EmptyUI text="\u6682\u65E0\u6570\u636E" />
  </Space>
);`},"sic-ui":{type:"NPM",value:"0.9.0"}},entry:"index.tsx"},context:{"sic-ui":I},renderOpts:{compile:function(){var m=i()(l()().mark(function r(){var s,d=arguments;return l()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,e.e(250).then(e.bind(e,90250));case 2:return n.abrupt("return",(s=n.sent).default.apply(s,d));case 3:case"end":return n.stop()}},r)}));function t(){return m.apply(this,arguments)}return t}()}}}},85005:function(c,u,e){e.r(u),e.d(u,{texts:function(){return o}});const o=[{value:"\u{1F48E} \u57FA\u7840\u4F7F\u7528",paraId:0,tocIndex:0},{value:"EmptyUI",paraId:1,tocIndex:1},{value:"\u5C5E\u6027",paraId:2,tocIndex:1},{value:"\u8BF4\u660E",paraId:2,tocIndex:1},{value:"\u7C7B\u578B",paraId:2,tocIndex:1},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:1},{value:"\u662F\u5426\u5FC5\u4F20",paraId:2,tocIndex:1},{value:"className",paraId:2,tocIndex:1},{value:"\u7C7B\u540D",paraId:2,tocIndex:1},{value:"String",paraId:2,tocIndex:1},{value:"-",paraId:2,tocIndex:1},{value:"\u5426",paraId:2,tocIndex:1},{value:"text",paraId:2,tocIndex:1},{value:"\u6587\u6848",paraId:2,tocIndex:1},{value:"String",paraId:2,tocIndex:1},{value:"-",paraId:2,tocIndex:1},{value:"\u5426",paraId:2,tocIndex:1}]}}]);
