"use strict";(self.webpackChunksic_ui=self.webpackChunksic_ui||[]).push([[892],{55040:function(i,s,e){e.r(s),e.d(s,{demos:function(){return p}});var _=e(43953),r=e.n(_),I=e(91184),m=e.n(I),a=e(38497),v=e(39625),c=e(23888),p={"emptyui-demo-0":{component:a.memo(a.lazy(m()(r()().mark(function o(){var u,d,n,l;return r()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,Promise.resolve().then(e.bind(e,23888));case 2:return u=t.sent,d=u.Space,n=u.EmptyUI,l=u.ImageUI,t.abrupt("return",{default:function(){return a.createElement(d,null,a.createElement(n,null),a.createElement(n,{image:a.createElement(l,{src:"https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",width:177,height:144})}),a.createElement(n,{text:"\u6682\u65E0\u6570\u636E"}))}});case 7:case"end":return t.stop()}},o)})))),asset:{type:"BLOCK",id:"emptyui-demo-0",refAtomIds:["EmptyUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { Space, EmptyUI, ImageUI } from 'sic-ui';\r
\r
export default () => (\r
  <Space>\r
    <EmptyUI />\r
    <EmptyUI\r
      image={<ImageUI src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" width={177} height={144} />}\r
    />\r
    <EmptyUI text="\u6682\u65E0\u6570\u636E" />\r
  </Space>\r
);`},"sic-ui":{type:"NPM",value:"0.4.29"}},entry:"index.tsx"},context:{"sic-ui":c},renderOpts:{compile:function(){var o=m()(r()().mark(function d(){var n,l=arguments;return r()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,e.e(4321).then(e.bind(e,14321));case 2:return t.abrupt("return",(n=t.sent).default.apply(n,l));case 3:case"end":return t.stop()}},d)}));function u(){return o.apply(this,arguments)}return u}()}}}},8375:function(i,s,e){e.r(s),e.d(s,{texts:function(){return r}});var _=e(39625);const r=[{value:"\u56FD\u4FE1\u7075\u5DE5\u540E\u53F0\u7BA1\u7406\u7CFB\u7EDF-\u7A7A\u72B6\u6001\u7EC4\u4EF6",paraId:0},{value:"\u{1F48E} \u57FA\u7840\u4F7F\u7528",paraId:1,tocIndex:2},{value:"EmptyUI",paraId:2,tocIndex:3},{value:"\u5C5E\u6027",paraId:3,tocIndex:3},{value:"\u8BF4\u660E",paraId:3,tocIndex:3},{value:"\u7C7B\u578B",paraId:3,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:3,tocIndex:3},{value:"\u662F\u5426\u5FC5\u4F20",paraId:3,tocIndex:3},{value:"className",paraId:3,tocIndex:3},{value:"\u7C7B\u540D",paraId:3,tocIndex:3},{value:"String",paraId:3,tocIndex:3},{value:"-",paraId:3,tocIndex:3},{value:"\u5426",paraId:3,tocIndex:3},{value:"text",paraId:3,tocIndex:3},{value:"\u6587\u6848",paraId:3,tocIndex:3},{value:"String",paraId:3,tocIndex:3},{value:"-",paraId:3,tocIndex:3},{value:"\u5426",paraId:3,tocIndex:3}]}}]);
