"use strict";(self.webpackChunksic_ui=self.webpackChunksic_ui||[]).push([[892],{82883:function(p,u,e){e.r(u),e.d(u,{demos:function(){return c}});var o=e(15009),r=e.n(o),I=e(99289),i=e.n(I),t=e(67294),E=e(41270),c={"emptyui-demo-0":{component:t.memo(t.lazy(i()(r()().mark(function m(){var d,s,n,l;return r()().wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,Promise.resolve().then(e.bind(e,42081));case 2:return d=a.sent,s=d.Space,n=d.EmptyUI,l=d.ImageUI,a.abrupt("return",{default:function(){return t.createElement(s,null,t.createElement(n,null),t.createElement(n,{image:t.createElement(l,{src:"https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",width:177,height:144})}),t.createElement(n,{text:"\u6682\u65E0\u6570\u636E"}))}});case 7:case"end":return a.stop()}},m)})))),asset:{type:"BLOCK",id:"emptyui-demo-0",refAtomIds:["EmptyUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { Space, EmptyUI, ImageUI } from 'sic-ui';\r
\r
export default () => (\r
  <Space>\r
    <EmptyUI />\r
    <EmptyUI\r
      image={<ImageUI src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" width={177} height={144} />}\r
    />\r
    <EmptyUI text="\u6682\u65E0\u6570\u636E" />\r
  </Space>\r
);`},"sic-ui":{type:"NPM",value:"0.4.28"}},entry:"index.tsx"},context:{"sic-ui":e(42081)},renderOpts:{compile:function(){var m=i()(r()().mark(function s(){var n,l=arguments;return r()().wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,e.e(4019).then(e.bind(e,4019));case 2:return a.abrupt("return",(n=a.sent).default.apply(n,l));case 3:case"end":return a.stop()}},s)}));function d(){return m.apply(this,arguments)}return d}()}}}},85005:function(p,u,e){e.r(u),e.d(u,{texts:function(){return r}});var o=e(41270);const r=[{value:"\u56FD\u4FE1\u7075\u5DE5\u540E\u53F0\u7BA1\u7406\u7CFB\u7EDF-\u7A7A\u72B6\u6001\u7EC4\u4EF6",paraId:0},{value:"\u{1F48E} \u57FA\u7840\u4F7F\u7528",paraId:1,tocIndex:2},{value:"EmptyUI",paraId:2,tocIndex:3},{value:"\u5C5E\u6027",paraId:3,tocIndex:3},{value:"\u8BF4\u660E",paraId:3,tocIndex:3},{value:"\u7C7B\u578B",paraId:3,tocIndex:3},{value:"\u9ED8\u8BA4\u503C",paraId:3,tocIndex:3},{value:"\u662F\u5426\u5FC5\u4F20",paraId:3,tocIndex:3},{value:"className",paraId:3,tocIndex:3},{value:"\u7C7B\u540D",paraId:3,tocIndex:3},{value:"String",paraId:3,tocIndex:3},{value:"-",paraId:3,tocIndex:3},{value:"\u5426",paraId:3,tocIndex:3},{value:"text",paraId:3,tocIndex:3},{value:"\u6587\u6848",paraId:3,tocIndex:3},{value:"String",paraId:3,tocIndex:3},{value:"-",paraId:3,tocIndex:3},{value:"\u5426",paraId:3,tocIndex:3}]}}]);
