import '@icon-park/react/styles/index.css';
import './index.scss';
export { default as BackUI } from './BackUI';
export { default as IconUI } from './IconUI';
export { default as TagUI } from './TagUI';
export { default as TestUI } from './TestUI';
export { default as SelectUI } from './SelectUI';
export { default as ButtonUI } from './ButtonUI';
export { default as SwitchUI } from './SwitchUI';
export { default as TextUI } from './TextUI';
export { default as SearchUI } from './SearchUI';
export { default as ModalUI } from './ModalUI';
export { default as LoadingUI } from './LoadingUI';
export { default as FormUI } from './FormUI';
export { default as DescribeUI } from './DescribeUI';
export { default as CellUI } from './CellUI';
export { default as NotificationUI } from './NotificationUI';
export { default as TableUI } from './TableUI';
export { default as AnchorUI } from './AnchorUI';
export { default as InputUI } from './InputUI';
export { default as UploadUI } from './UploadUI';
export { default as ImageUI } from './ImageUI';
